name: Update Dependency Graph

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependency Graph
        uses: scalacenter/sbt-dependency-submission@v3
